version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
      - FLASK_APP=app.py
    depends_on:
      app_database:
        condition: service_healthy

  app_database:
    image: postgres:14-alpine3.19

